### ISSUE TITLE
MoveTargetOutOfBoundsException

### ISSUE THREAD

**Issue by umarambh** [mozilla/GitHub_Selenium#5] opened 2019-09-20 21:05 UTC
MoveTargetOutOfBoundsException is occurring in more recent times when used in Drag and drop scenario. This exception started to observed first with vertical movement and slowly with horizontal drag and drop actions too. Wanted someone to look into.
Error description:- MoveTargetOutOfBoundsException: Message: (1428, 545) is out of bounds of viewport width (1152) and height (847).
Also checked to make sure browser window is maximized, Firefox version 69.0, OS tested on : Mac OS 10.14.5 and Linux.

**Comment by umarambh** [comment] 2019-09-20 21:10
MoveTargetOutOfBoundsException is occurring in more recent times when used in Drag and drop scenario. This exception started to observed first with vertical movement and slowly with horizontal drag and drop actions too. Wanted someone to look into. 
Error description:- MoveTargetOutOfBoundsException: Message: (1428, 545) is out of bounds of viewport width (1152) and height (847). 
Also checked to make sure browser window is maximized, Firefox version 69.0, OS tested on : Mac OS 10.14.5 and Linux.

**Comment by hwine** [comment] 2019-11-20 00:24
@umarambh -- this sounds like a problem with Selenium itself. If it's occurring only with GitHub_Selenium, please attach a steps to reproduce.

**Comment by hwine** [comment] 2019-11-20 00:28
A duplicate of #6

**Closed as completed by hwine** 2019-11-20 00:28 UTC
Labels: duplicate
